### PR TITLE
GAuth.setToken has a bug

### PR DESCRIPTION
**Pull request by sokolandia**
According to the reference docs for [OAuth 2.0 Token Object](https://developers.google.com/api-client-library/javascript/reference/referencedocs#OAuth20TokenObject), this line $window.gapi.auth.setToken(token) should look like this $window.gapi.auth.setToken({ access_token: token })

### CODE REVIEW

**Comment by maximepvrt** [comment]
No, the method param is the Google Token Object in my setToken method :)
If you like this module, you can "star" this projet

**Comment by sokolandia** [comment]
Oh, I get it, my bad. What do you mean by starting a project?

**Comment by maximepvrt** [comment]
:smile:
https://github.com/maximepvrt/angular-google-gapi/ in top of page (watch, star, fork)

**Comment by sokolandia** [comment]
you mean to star the project, ah, sure. just regisrtered on github.

**Comment by maximepvrt** [comment]
thanks :+1: oh goood
/!\ use issue for ask a question

**Pull request closed without merging**
