### PR TITLE
change the app.run setScopes examplel

### PR DESCRIPTION
**Pull request by zivkaziv**
change it to be setScopes and not setScope

### CODE REVIEW

**Comment by maximepvrt** [comment]
why ? it's setScope in source code

**Comment by zivkaziv** [comment]
That's strange, in my code it throw exception that setScope doesn't exist,
but setScopes does..
Any idea?

**Comment by maximepvrt** [comment]
you have update this modules ? before the api was with setScopes

**Comment by zivkaziv** [comment]
I'm checking it

**Comment by zivkaziv** [comment]
Hi Max,

We are using version 0.1.2

**Comment by maximepvrt** [comment]
ok ! update your angular-google-gapi with version 0.1.3 :smile: 
If you like this module, you can "star" this projet

**Comment by zivkaziv** [comment]
Sure, thanks...
Anyway, why don't you support backward?

**Comment by maximepvrt** [comment]
you can stay in your version, but use setScopes

**Pull request closed without merging**
