### PR TITLE
add createRequest to support batching

### PR DESCRIPTION
**Pull request by mmautner**
You need request objects to utilize the batch API, so I exposed that:

https://developers.google.com/api-client-library/javascript/features/batch

### CODE REVIEW

**Comment by maximepvrt** [comment]
please create a pull request on develop branch
thanks

**Comment by maximepvrt** [comment]
I have added your code on the develop branch

**Comment by mmautner** [comment]
hey thanks :) :+1:

**Comment by ruben-lopez** [comment]
Hello,
maybe you can help me, how can I add batch requests and then execute them using the angular module?

I was trying something but finally couldn't manage to do it..

Thanks!

**Pull request closed without merging**
